@uri = http://localhost:5525
@cookie = session_id=9e401e22-0aa7-4c1d-9ea7-c2dc6d11005b;


### Login
POST {{uri}}/api/login HTTP/1.1
content-type: application/json
Origin: {{uri}}

{
    "userid": "admin",
    "password": "admin"
}


### Get member list
GET {{uri}}/api/admin/member/scratch
Cookie: {{cookie}}

### Add member
POST {{uri}}/api/admin/member/scratch/1
Cookie: {{cookie}}
