@uri = http://localhost:5525
@cookie = session_id=032aaf58-cf63-4eeb-80ad-b8d2230e6a21; 


### Login
POST {{uri}}/api/login HTTP/1.1
content-type: application/json
Origin: {{uri}}

{
    "name": "admin",
    "password": "admin"
}

