@uri = http://localhost:5525
@cookie = session_id=032aaf58-cf63-4eeb-80ad-b8d2230e6a21; 

### health
GET {{uri}}/api/health

### Login
POST {{uri}}/api/login HTTP/1.1
content-type: application/json
Origin: {{uri}}

{
    "name": "admin",
    "password": "admin"
}

### Logout
GET {{uri}}/api/logout HTTP/1.1
content-type: application/json
Cookie: {{cookie}}

### Signup
POST {{uri}}/api/signup HTTP/1.1
content-type: application/json
Origin: {{uri}}

{
    "username": "bab2",
    "email": "edp1096@naver.com",
    "password": "bab2"
}

### Myinfo
GET {{uri}}/api/myinfo HTTP/1.1
content-type: application/json
Cookie: {{cookie}}

### Update
PUT {{uri}}/api/myinfo HTTP/1.1
content-type: application/json
Cookie: {{cookie}}

{
    "username": "admin",
    "old-password": "admin",
    "password": "admin"
}

### Delete
DELETE {{uri}}/api/myinfo HTTP/1.1
content-type: application/json
Cookie: {{cookie}}
