@uri=http://localhost:2510
# @uri=http://enjoytools.net:2510

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBhLmNvbSIsImFkbWluIjoiWSIsInJlZnJlc2gtdW50aWwiOjE2MjY1MDIyNDcsImV4cCI6MTYyMzk5NjY0N30.ZAg_DFvwGWQcDXSSQx1niVlLxJ6_bSlBeyIFKnZUs1s

### HTML contents
GET {{uri}}/board?code=board0 HTTP/1.1

### Read HTML Contents
GET {{uri}}/board?code=board1&mode=read&id=1 HTTP/1.1


## Basic board

### Read contents list
POST {{uri}}/api/basic-board/contents HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "keywords": [],
    "options": {
        "count": 1
    },
    "table": "BOARD1"
}

### Read Contents
POST {{uri}}/api/basic-board/contents HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "keywords": [
        {
            "idx": "4"
        }
    ],
    "options": {
        "count": 1
    },
    "table": "BOARD1"
}

### Write a content
PUT {{uri}}/api/basic-board/contents HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "data": {
        "title": "타이틀",
        "content": "게시물 내용",
        "writer-idx": "-1",
        "writer-name": "ㅇㅇ",
        "writer-password": "1234"
    },
    "table": "BOARD1"
}

### Edit a content
PATCH {{uri}}/api/basic-board/contents HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "data": {
        "idx": "1",
        "title": "Post title",
        "content": "Post text lorem ipsum",
        "writer-idx": "-1",
        "writer-name": "ㅇㅇ",
        "writer-password": "1234"
    },
    "table": "BOARD1"
}

### Delete a content
DELETE {{uri}}/api/basic-board/contents HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "data": {
        "idx": "1"
    },
    "table": "BOARD1"
}

### Total page of content
POST {{uri}}/api/basic-board/total-page HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "keywords": [],
    "options": {
        "count": 5
    },
    "table": "BOARD0"
}



## Custom board / tablelist

### Read contents - tablelist
POST {{uri}}/api/custom-board/contents-list HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "keywords": [],
    "options": {
        "order": "desc",
        "count": "5"
    },
    "columns": [
        "IDX",
        "NAME",
        "CONTENT",
        "CREATOR"
    ],
    "table": "BOARD0"
}

### Read contents - custom board
POST {{uri}}/api/custom-board/contents-list HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "keywords": [],
    "options": {
        "order": "desc",
        "count": "5"
    },
    "columns": [
        "IDX",
        "NAME",
        "AGENCY"
    ],
    "table": "CBOARD3"
}

### Read a content - custom board
POST {{uri}}/api/custom-board/contents-list HTTP/1.1
content-type: application/json

{
    "keywords": [{"IDX": "1"}],
    "options": {
        "count": "1"
    },
    "columns": [
        "IDX",
        "NAME",
        "AGENCY"
    ],
    "table": "CBOARD3"
}

### Write a content - custom-tablelist
PUT {{uri}}/api/custom-board/contents-list HTTP/1.1
content-type: application/json

{
    "data": {
        "NAME": "이름이믊",
        "CONTENT": "내용 내용",
        "CREATOR": "ㅇㅇ"
    },
    "table": "BOARD0"
}

### Write a content - custom-board
PUT {{uri}}/api/custom-board/contents-list HTTP/1.1
content-type: application/json

{
    "data":{
        "NAME": "김개동",
        "AGENCY": "우리집"
    },
    "table":"CBOARD3"
}


### Edit a content
PATCH {{uri}}/api/custom-board/contents-list HTTP/1.1
content-type: application/json

{
    "data": {
        "IDX": 1,
        "NAME": "훈민정음",
        "CONTENT": "가나다라마바사아자차카타파하",
        "CREATOR": "세종대왕"
    },
    "table": "BOARD0"
}


### Total page of content
POST {{uri}}/api/custom-board/total-page HTTP/1.1
content-type: application/json

{
    "keywords": [],
    "options": {
        "count": 5
    },
    "table": "CBOARD3"
}

### Paging - Same as below search except keywords
POST {{uri}}/api/custom-board/contents-list HTTP/1.1
content-type: application/json

{
    "keywords": [],
    "options": {
        "page": 0,
        "count": 3,
        "order": "desc"
    },
    "columns": [
        "IDX",
        "NAME",
        "CONTENT",
        "CREATOR"
    ],
    "table": "BOARD0"
}
