@uri=http://localhost:2510
# @uri=http://enjoytools.net:2510


### Read comments of one post
POST {{uri}}/api/comments HTTP/1.1
content-type: application/json

{
    "keywords": [
        {
            "bidx": "1"
        }
    ],
    "options": {
        "count": 10
    },
    "table": "DOOLYFAM"
}

### Write a comment
PUT {{uri}}/api/comments HTTP/1.1
content-type: application/json

{
    "data": {
        "bidx": "1",
        "content": "댓글 내용",
        "writer-idx": "-1",
        "writer-name": "ㅇㅇ",
        "writer-password": "1234"
    },
    "table": "DOOLYFAM"
}