@uri = http://localhost:5525
@cookie = session_id=54c8da6e-fb86-4e79-807a-da0d32f97ab8; 


### Login
POST {{uri}}/api/login HTTP/1.1
content-type: application/json
Origin: {{uri}}

{
    "userid": "admin",
    "password": "admin"
}

### User list
GET {{uri}}/api/admin/user
Content-Type: application/json
Cookie: {{cookie}}

### User list - page
GET {{uri}}/api/admin/user?page=3
Content-Type: application/json
Cookie: {{cookie}}

### User list - search
GET {{uri}}/api/admin/user?search=ad
Content-Type: application/json
Cookie: {{cookie}}

### Add user
POST {{uri}}/api/admin/user
Content-Type: application/json
Cookie: {{cookie}}

{
    "userid": "user",
    "password": "user",
    "email": "user@example.com",
    "grade": "pending_user",
    "approval": "N"
}

### Edit user
PUT {{uri}}/api/admin/user
Content-Type: application/json
Cookie: {{cookie}}

[
    {
        "idx": "17",
        "userid": "userb",
        "email": "userb@example.com",
        "grade": "pending_user"
    }
]

### Delete user - Just update grade as resigned status
DELETE {{uri}}/api/admin/user
Content-Type: application/json
Cookie: {{cookie}}

[
    { "idx": "15" },
    { "idx": "17" }
]
