@uri = http://localhost:5525
@cookie = session_id=c95f9624-c67c-4093-9e9f-339d5c2761af; 


### Login
POST {{uri}}/api/login HTTP/1.1
Content-Type: application/json
Origin: {{uri}}

{
    "userid": "admin",
    "password": "admin"
}

### Content - Write
POST {{uri}}/api/board/content/misc1 HTTP/1.1
Content-Type: application/json
Cookie: {{cookie}}

{
    "title": "My test #1",
    "content": "Nise to mit u lol~\n^_^_^_^& <^-^>'",
    "author-idx": 1,
    "author-name": "admin"
}

### Content - List
GET {{uri}}/api/board/content/misc1 HTTP/1.1
Cookie: {{cookie}}

### Content - Read
GET {{uri}}/api/board/content/misc1/1 HTTP/1.1
Cookie: {{cookie}}
