@uri=http://localhost:2510
# @uri=http://enjoytools.net:2510

### Select users
POST {{uri}}/api/user/login HTTP/1.1
content-type: application/json

{
    "keywords": {
        "NAME": "bab2",
        "PASSWORD": "1234"
    },
    "columns": [
        "IDX",
        "NAME",
        "PASSWORD",
        "EMAIL",
        "ADMIN",
        "APPROVAL",
        "REG_DTTM",
    ],
    "table": "USERS"
}


### Verify token
POST {{uri}}/api/user/token/verify HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYmFiMiIsImVtYWlsIjoiZWRwMTA5NkBuYXZlci5jb20iLCJhZG1pbiI6IlkiLCJyZWZyZXNoLXVudGlsIjoxNjI2MzU2NTE1LCJleHAiOjE2MjM4NjE2OTd9.PtGye0cLiWqPjZB0AwXqSxH2ojGtja0_a8nT6WqUaQE


### Reissue token
GET {{uri}}/api/user/token/verify HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYmFiMiIsImVtYWlsIjoiZWRwMTA5NkBuYXZlci5jb20iLCJhZG1pbiI6IlkiLCJyZWZyZXNoLXVudGlsIjoxNjI2MzU2NTE1LCJleHAiOjE2MjM4NjE2OTd9.PtGye0cLiWqPjZB0AwXqSxH2ojGtja0_a8nT6WqUaQE
