@uri = http://localhost:5525
@cookie = session_id=a7b03128-68d3-4190-b131-43a8c1ce1152;

### health
GET {{uri}}/api/health

### Login
POST {{uri}}/api/login HTTP/1.1
content-type: application/json
Origin: {{uri}}

{
    "name": "bab2",
    "password": "bab2"
}

### Logout
GET {{uri}}/api/logout HTTP/1.1
content-type: application/json
Cookie: {{cookie}}

### Signup
POST {{uri}}/api/signup HTTP/1.1
content-type: application/json
Origin: {{uri}}

{
    "username": "bab2",
    "email": "edp1096@naver.com",
    "password": "bab2"
}

### Myinfo
GET {{uri}}/api/myinfo HTTP/1.1
content-type: application/json
Cookie: {{cookie}}

### Update
PUT {{uri}}/api/myinfo HTTP/1.1
content-type: application/json
Cookie: {{cookie}}

{
    "username": "admin",
    "old-password": "admin",
    "password": "admin"
}

### Delete
DELETE {{uri}}/api/myinfo HTTP/1.1
content-type: application/json
Cookie: {{cookie}}
