@uri=http://localhost:2510
# @uri=http://enjoytools.net:2510


### Select all fields
GET {{uri}}/api/admin/users HTTP/1.1


### Add user fields
PUT {{uri}}/api/admin/users HTTP/1.1
content-type: application/json

[
    {
        "name": "Gender",
        "code": "gender",
        "type": "text",
        "column": "GENDER",
        "order": 2
    }
]

### Modify user fields
PATCH {{uri}}/api/admin/users HTTP/1.1
content-type: application/json

{
    "idx": 2,
    "name": "Country",
    "code": "country",
    "type": "text",
    "column": "COUNTRY",
    "order": 3
}

### DELETE board
DELETE {{uri}}/api/admin/board/3 HTTP/1.1
