@uri = http://localhost:5525
@cookie = session_id=a5bf29dc-a203-428e-8c4f-62541d57b640; 


### Login
POST {{uri}}/api/login HTTP/1.1
content-type: application/json
Origin: {{uri}}

{
    "userid": "admin",
    "password": "admin"
}

### Board list
GET {{uri}}/api/admin/boards
Content-Type: application/json
Cookie: {{cookie}}

### Board list - search
GET {{uri}}/api/admin/boards?search=mis
Content-Type: application/json
Cookie: {{cookie}}

### Add board
POST {{uri}}/api/admin/boards
Content-Type: application/json
Cookie: {{cookie}}

{
    "board-name": "misc1",
    "board-code": "misc1",
    "board-type": "board",
    "board-table": "board_misc1",
    "comment-table": "comment_misc1",
    "grant-read": "guest",
    "grant-write": "regular_user",
    "grant-comment": "regular_user",
    "grant-upload": "regular_user",
    "fields": null
}

### Edit board
PUT {{uri}}/api/admin/boards
Content-Type: application/json
Cookie: {{cookie}}

[
    {
        "idx": "1",
        "board-name": "misc1",
        "board-code": "misc1",
        "board-type": "board",
        "board-table": "board_misc1",
        "comment-table": "comment_misc1",
        "grant-read": "guest",
        "grant-write": "regular_user",
        "grant-comment": "regular_user",
        "grant-upload": "regular_user",
        "fields": null
    }
]

### Delete board
DELETE {{uri}}/api/admin/boards
Content-Type: application/json
Cookie: {{cookie}}

[
    { "idx": "1" },
    { "idx": "9" }
]
