@uri=http://localhost:2510

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHgiOiIzNiIsInVzZXJuYW1lIjoidXNlcjEiLCJlbWFpbCI6InVzZXJAYS5jb20iLCJhZG1pbiI6Ik4iLCJyZWZyZXNoLXVudGlsIjoxNjI2ODkxMzE1LCJleHAiOjE2MjQzODU3MTV9.ydN1bE9nNjRMFz5S0rE2pf7pilxwiLaO-SH1a2mRopA

### List of contents
POST {{uri}}/api/basic-board/contents?code=board1 HTTP/1.1
# Authorization: Bearer {{token}}
content-type: application/json

{
    "keywords": [],
    "options": {
        "count": 10
    },
    "table": "BOARD1"
}

### Read Content
POST {{uri}}/api/basic-board/contents?code=board1 HTTP/1.1
# Authorization: Bearer {{token}}
content-type: application/json

{
    "keywords": [{ "idx": "2" }],
    "options": { "count": 10 },
    "table": "BOARD1"
}

### Write a content
PUT {{uri}}/api/basic-board/contents?code=board1&mode=write HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "data": {
        "title": "my title user1",
        "content": "my contents texts user1",
        "is-member": "Y",
        "writer-name": "anonymous1_no_effect",
        "writer-password": "1234_no_effect"
    },
    "table": "BOARD1"
}

### Edit a content
PATCH {{uri}}/api/basic-board/contents?code=board1&mode=edit HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "data": {
        "idx": "6",
        "title": "Post title",
        "content": "Post text lorem ipsum",
        "writer-name": "user1"
    },
    "table": "BOARD1"
}

### Edit a content - anonymous post
PATCH {{uri}}/api/basic-board/contents?code=board1&mode=edit HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "data": {
        "idx": "2",
        "title": "Post title",
        "content": "Post text lorem ipsum",
        "writer-name": "dd"
    },
    "table": "BOARD1"
}

### Delete a content
DELETE {{uri}}/api/basic-board/contents?code=board1&mode=delete HTTP/1.1
content-type: application/json

{
    "data": {
        "idx": "2",
        "writer-password": null
    },
    "table": "BOARD1"
}

### Total pages of contents
POST {{uri}}/api/basic-board/total-page?code=board1 HTTP/1.1
content-type: application/json

{
    "keywords": [],
    "options": {
        "count": 5
    },
    "table": "BOARD1"
}
