@uri=http://localhost:2510

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHgiOiIzNiIsInVzZXJuYW1lIjoidXNlcjEiLCJlbWFpbCI6InVzZXJAYS5jb20iLCJhZG1pbiI6Ik4iLCJyZWZyZXNoLXVudGlsIjoxNjI4NzU5NDI0LCJleHAiOjE2MjYyNTM4MjR9.OfjQ467RY2oXRkRR5_ZhF2xvY15o_EBChXqZus0CN-o

## Basic board

### Read comments of one post
POST {{uri}}/api/comments?code=board1&mode=read HTTP/1.1
# Authorization: Bearer {{token}}
content-type: application/json

{
    "keywords": [
        {
            "bidx": "1"
        }
    ],
    "options": {
        "count": 10
    },
    "table": "BOARD1"
}

### Write a comment
PUT {{uri}}/api/comments?code=board1&mode=write HTTP/1.1
# Authorization: Bearer {{token}}
content-type: application/json

{
    "data": {
        "bidx": "1",
        "content": "This is comment",
        "writer-name": "anonym",
        "writer-password": "1234"
    },
    "table": "BOARD1"
}

### Edit a comment
PATCH {{uri}}/api/comments?code=board1&mode=edit HTTP/1.1
# Authorization: Bearer {{token}}
content-type: application/json

{
    "data": {
        "idx": "2",
        "bidx": "1",
        "content": "commentaaa text :)",
        "writer-name": "dd",
        "writer-password": "1234"
    },
    "table": "BOARD1"
}

### Delete a comment
DELETE {{uri}}/api/comments?code=board1&mode=delete HTTP/1.1
# Authorization: Bearer {{token}}
content-type: application/json

{
    "data": {
        "idx": "16",
        "bidx": "5",
    },
    "table": "BOARD1"
}


## Custom board

### Read comments which related to content
POST {{uri}}/api/comments?code=cboard1&mode=read HTTP/1.1
# Authorization: Bearer {{token}}
content-type: application/json

{
    "keywords": [
        {
            "bidx": "5"
        }
    ],
    "options": {
        "count": 2
    },
    "table": "CBOARD1"
}

### Write a comment - When using token, writer-name & writer-password will be ignored
PUT {{uri}}/api/comments?code=cboard1&mode=write HTTP/1.1
# Authorization: Bearer {{token}}
content-type: application/json

{
    "data": {
        "bidx": "5",
        "content": "This is a comment!!",
        "writer-name": "who",
        "writer-password": "1234"
    },
    "table": "CBOARD1"
}

### Edit a comment
PATCH {{uri}}/api/comments?code=cboard1&mode=edit HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "data": {
        "idx": "14",
        "bidx": "5",
        "content": "Edited comment ;-)",
        "writer-name": "user1",
        "writer-name": "1234"
    },
    "table": "CBOARD1"
}
