@uri=http://localhost:2510

## HTML

### List of contents
GET {{uri}}/board?code=board1 HTTP/1.1

### Read content
GET {{uri}}/board?code=board1&mode=read&id=1 HTTP/1.1


## Basic board

### List of contents
POST {{uri}}/api/basic-board/contents?code=board1 HTTP/1.1
content-type: application/json

{
    "keywords": [],
    "options": {
        "count": 10
    },
    "table": "BOARD1"
}

### Read Content
POST {{uri}}/api/basic-board/contents?code=board1 HTTP/1.1
content-type: application/json

{
    "keywords": [{ "idx": "1" }],
    "options": { "count": 10 },
    "table": "BOARD1"
}

### Write a content
PUT {{uri}}/api/basic-board/contents?code=board1&mode=write HTTP/1.1
content-type: application/json

{
    "data": {
        "title": "my title",
        "content": "my contents texts",
        "writer-name": "anonymous1",
        "writer-password": "1234"
    },
    "table": "BOARD1"
}

### Edit a content
PATCH {{uri}}/api/basic-board/contents?code=board1&mode=edit HTTP/1.1
content-type: application/json

{
    "data": {
        "idx": "1",
        "title": "Post title",
        "content": "Post text lorem ipsum",
        "writer-name": "anonymous1",
        "writer-password": "1234"
    },
    "table": "BOARD1"
}

### Delete a content
DELETE {{uri}}/api/basic-board/contents?code=board1&mode=delete HTTP/1.1
content-type: application/json

{
    "data": {
        "idx": "1",
        "writer-password": "1234"
    },
    "table": "BOARD1"
}

### Total pages of contents
POST {{uri}}/api/basic-board/total-page?code=board1 HTTP/1.1
content-type: application/json

{
    "keywords": [],
    "options": {
        "count": 5
    },
    "table": "BOARD1"
}



## Custom board / tablelist

### Read contents - tablelist
POST {{uri}}/api/custom-board/contents HTTP/1.1
content-type: application/json

{
    "keywords": [],
    "options": {
        "order": "desc",
        "count": "5"
    },
    "columns": [
        "IDX",
        "NAME",
        "CONTENT",
        "CREATOR"
    ],
    "table": "BOARD0"
}

### Read contents - custom board
POST {{uri}}/api/custom-board/contents?code=cboard1 HTTP/1.1
content-type: application/json

{
    "keywords": [],
    "options": {
        "order": "desc",
        "count": "5"
    },
    "columns": [
        "IDX",
        "NAME",
        "AGENCY"
    ],
    "table": "CBOARD1"
}

### Read a content - custom board
POST {{uri}}/api/custom-board/contents?code=cboard1 HTTP/1.1
content-type: application/json

{
    "keywords": [{"IDX": "1"}],
    "options": {
        "count": "1"
    },
    "columns": [
        "IDX",
        "NAME",
        "AGENCY"
    ],
    "table": "CBOARD1"
}

### Write a content - custom-tablelist
PUT {{uri}}/api/custom-board/contents HTTP/1.1
content-type: application/json

{
    "data": {
        "NAME": "My Title",
        "AGE": "3000",
        "PHONE": "12345678",
    },
    "table": "CUSTOMLIST1"
}

### Write a content - custom-board
PUT {{uri}}/api/custom-board/contents HTTP/1.1
content-type: application/json

{
    "data":{
        "NAME": "John Doe",
        "AGENCY": "My home office"
    },
    "table":"CBOARD1"
}

### Edit a content
PATCH {{uri}}/api/custom-board/contents HTTP/1.1
content-type: application/json

{
    "data": {
        "IDX": 1,
        "CONTENT": "Lorem ipsum fox",
        "AGENCY": "Jane Waldo"
    },
    "table": "CBOARD1"
}

### Total page of content
POST {{uri}}/api/custom-board/total-page HTTP/1.1
content-type: application/json

{
    "keywords": [],
    "options": {
        "count": 5
    },
    "table": "CBOARD3"
}

### Paging - Same as below search except keywords
POST {{uri}}/api/custom-board/contents HTTP/1.1
content-type: application/json

{
    "keywords": [],
    "options": {
        "page": 0,
        "count": 3,
        "order": "desc"
    },
    "columns": [
        "IDX",
        "NAME",
        "CONTENT",
        "CREATOR"
    ],
    "table": "BOARD0"
}
