@uri=http://localhost:2510
# @uri=http://enjoytools.net:2510

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHgiOiIyIiwidXNlcm5hbWUiOiJ1c2VyMSIsImVtYWlsIjoidXNlcjFAYS5jb20iLCJhZG1pbiI6Ik4iLCJyZWZyZXNoLXVudGlsIjoxNjI4NTIzMjE0LCJleHAiOjE2MjYwMTc2MTR9.KbqQXJ58kK-EJiTo8YIbkfFgmrzFi76vrxh2cmVqcwU


## Custom tablelist

### Read contents - tablelist
POST {{uri}}/api/custom-board/contents?code=customlist2 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "keywords": [],
    "options": {
        "order": "desc",
        "count": "5"
    },
    "columns": [
        "IS_MEMBER",
        "WRITER_NAME",
        "IDX",
        "NAME",
        "AGE",
        "PHONE"
    ],
    "table": "CUSTOMLIST2"
}

### Write a content - custom-tablelist
PUT {{uri}}/api/custom-board/contents?code=customlist2 HTTP/1.1
# Authorization: Bearer {{token}}
content-type: application/json

{
    "data": {
        "WRITER_NAME": "user1",
        "name": "User1111",
        "age": "99",
        "phone": "321321321"
    },
    "table": "CUSTOMLIST2"
}

### Edit a content
PATCH {{uri}}/api/custom-board/contents?code=customlist2 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "data": {
        "IDX": 2,
        "WRITER_NAME": "user1",
        "name": "User12",
        "age": "99",
        "phone": "321321321"
    },
    "table": "CUSTOMLIST2"
}

### Delete a content
DELETE {{uri}}/api/custom-board/contents?code=customlist2&mode=delete HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "data": { "IDX": 3 },
    "table": "CUSTOMLIST2"
}

### Total page of content
POST {{uri}}/api/custom-board/total-page?code=customlist2 HTTP/1.1
# Authorization: Bearer {{token}}
content-type: application/json

{
    "keywords": [],
    "options": {
        "count": 5
    },
    "table": "CUSTOMLIST2"
}
