@uri=http://localhost:2510
# @uri=http://enjoytools.net:2510

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHgiOiIzNiIsInVzZXJuYW1lIjoidXNlcjEiLCJlbWFpbCI6InVzZXJAYS5jb20iLCJhZG1pbiI6Ik4iLCJyZWZyZXNoLXVudGlsIjoxNjI4NjcwOTMxLCJleHAiOjE2MjYxNjUzMzF9.rHtfIY2h4TDm9UbkGfL_xmcA0jxz-Ygn1MHguwC7tOI


## Custom tablelist

### Read contents - tablelist
POST {{uri}}/api/custom-board/contents?code=customlist2 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "keywords": [],
    "options": {
        "order": "desc",
        "count": "5"
    },
    "columns": [
        "IS_MEMBER",
        "WRITER_NAME",
        "IDX",
        "NAME",
        "AGE",
        "PHONE"
    ],
    "table": "CUSTOMLIST2"
}

### Write a content - custom-tablelist
PUT {{uri}}/api/custom-board/contents?code=customlist2 HTTP/1.1
# Authorization: Bearer {{token}}
content-type: application/json

{
    "data": {
        "WRITER_NAME": "user1",
        "name": "User1111",
        "age": "99",
        "phone": "321321321"
    },
    "table": "CUSTOMLIST2"
}

### Edit a content
PATCH {{uri}}/api/custom-board/contents?code=customlist2&mode=edit HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "data": {
        "IDX": 1,
        "WRITER_NAME": "user2",
        "NAME": "John",
        "AGE": "22",
        "PHONE": "112233441234"
    },
    "table": "CUSTOMLIST2"
}

### Delete a content
DELETE {{uri}}/api/custom-board/contents?code=customlist1&mode=delete HTTP/1.1
# Authorization: Bearer {{token}}
content-type: application/json

{
    "data": { "IDX": 1 },
    "table": "CUSTOMLIST1"
}

### Total page of content
POST {{uri}}/api/custom-board/total-page?code=customlist2 HTTP/1.1
# Authorization: Bearer {{token}}
content-type: application/json

{
    "keywords": [],
    "options": {
        "count": 5
    },
    "table": "CUSTOMLIST2"
}
