@uri=http://localhost:2510
# @uri=http://enjoytools.net:2510

### Select users
POST {{uri}}/api/user/login HTTP/1.1
content-type: application/json

{
    "keywords": {
        "USERNAME": "user1",
        "PASSWORD": "user1"
    },
    "columns": [
        "IDX",
        "USERNAME",
        "PASSWORD",
        "EMAIL",
        "ADMIN",
        "APPROVAL",
        "REG_DTTM",
    ],
    "table": "USERS"
}


### Verify token
POST {{uri}}/api/user/token/verify HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBhLmNvbSIsImFkbWluIjoiWSIsInJlZnJlc2gtdW50aWwiOjE2MjY1MDIyNDcsImV4cCI6MTYyMzk5NjY0N30.ZAg_DFvwGWQcDXSSQx1niVlLxJ6_bSlBeyIFKnZUs1s


### Reissue token
GET {{uri}}/api/user/token/verify HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBhLmNvbSIsImFkbWluIjoiWSIsInJlZnJlc2gtdW50aWwiOjE2MjY1MDIyNDcsImV4cCI6MTYyMzk5NjY0N30.ZAg_DFvwGWQcDXSSQx1niVlLxJ6_bSlBeyIFKnZUs1s
