@uri = http://localhost:5525
@cookie = session_id=07bea9a9-be09-43c7-8905-0d8d0afc7bfa;


### Login
POST {{uri}}/api/login HTTP/1.1
Content-Type: application/json
Origin: {{uri}}

{
    "userid": "admin",
    "password": "admin"
}

### Comment - List
GET {{uri}}/api/board/misc/1/comment?page=2&count=2 HTTP/1.1

### Comment - Write
POST {{uri}}/api/board/misc/1/comment HTTP/1.1
Content-Type: application/json

{
    "author-idx": 1,
    "author-name": "admin",
    "content": "<p>This is a comment! Nice to meet you & <^-^>'</p>",
    "files": ""
}

### Comment - Update
PUT {{uri}}/api/board/misc/1/comment/1 HTTP/1.1
Content-Type: application/json

{
    "author-idx": 1,
    "author-name": "admin",
    "content": "<p>This is a comment! Edit!!</p>",
    "files": ""
}

### Comment - Delete
DELETE {{uri}}/api/board/misc/30/comment/11 HTTP/1.1
