@uri=http://localhost:2510
# @uri=http://enjoytools.net:2510

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHgiOiIxMzAiLCJ1c2VybmFtZSI6InVzZXIxIiwiZW1haWwiOiJ1c2VyMUBhLmNvbSIsImFkbWluIjoiXHUwMDNjbmlsXHUwMDNlIiwicmVmcmVzaC11bnRpbCI6MTYzMTQ1OTgwOSwiZXhwIjoxNjI4OTU0MjA5fQ.gyHBjnXvrSJcDbzGAxlM8WvFNAVRhokR79nKKKdjZqY


### Join a user
POST {{uri}}/api/user/join HTTP/1.1
content-type: application/json

{
    "USERNAME": "user13",
    "PASSWORD": "user13",
    "EMAIL": "user13@a.com",
    "ADMIN": "N"
}

### Get user info
POST {{uri}}/api/user/data HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "keywords": [],
    "options": {},
    "columns": [
        "IDX",
        "USERNAME",
        "PASSWORD",
        "EMAIL",
        "ADMIN",
        "APPROVAL",
        "REG_DTTM",
    ],
    "table": "USERS"
}

### Edit a user
POST {{uri}}/api/user/edit HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "IDX": 13,
    "USERNAME": "user100",
    "PASSWORD": "user100",
    "EMAIL": "user100@mymy.com",
    "ADMIN": "Y",
    "APPROVAL": "N"
}

### Delete user
DELETE {{uri}}/api/user/2 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

