@uri=http://localhost:2510
# @uri=http://enjoytools.net:2510

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHgiOiIxMyIsInVzZXJuYW1lIjoidXNlcjEiLCJlbWFpbCI6InVzZXIxQGEuY29tIiwiYWRtaW4iOiJOIiwicmVmcmVzaC11bnRpbCI6MTYzMTYyODgxMywiZXhwIjoxNjI5MTIzMjEzfQ.7gNm9DqLniQ66aVjLMREX4sE8umb16ksL2Flmsf_Iuk


### Join a user
POST {{uri}}/api/user/join HTTP/1.1
content-type: application/json

{
    "USERNAME": "user13",
    "PASSWORD": "user13",
    "EMAIL": "user13@a.com",
    "ADMIN": "N"
}

### Get user info
POST {{uri}}/api/user/data HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "keywords": [],
    "options": {},
    "columns": [
        "IDX",
        "USERNAME",
        "PASSWORD",
        "EMAIL",
        "ADMIN",
        "APPROVAL",
        "REG_DTTM",
    ],
    "table": "USERS"
}

### Edit a user
POST {{uri}}/api/user/edit HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "IDX": 13,
    "USERNAME": "user1",
    "PASSWORD": "user1",
    "EMAIL": "user1@mymy.com",
    "ADMIN": "N",
    "APPROVAL": "Y",
    "COUNTRY": "KR"
}

### Delete user
DELETE {{uri}}/api/user/2 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

